services:
  backend:
    build:
      context: ./backend
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8282:8000"
    volumes:
      - ./backend/recognition:/code/
      - ./backend/storage:/storage/
    depends_on:
      - redis
    env_file: .env

  ws-backend:
    build:
      context: ./backend
    command: python websocket.py
    ports:
      - "8888:8888"
    volumes:
      - ./backend/recognition:/code/
    depends_on:
      - redis
    env_file: .env

  queue-worker:
    build:
      context: ./backend
    entrypoint: python manage.py rqworker default --with-scheduler
    volumes:
      - ./backend/recognition:/code/
      - ./backend/storage:/storage/
    depends_on:
      - redis
    env_file: .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
