services:
  backend:
    build:
      context: ./backend
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8282:8000"
    volumes:
      - ./backend/recognition:/code/
    depends_on:
      - redis
    env_file: .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
